contacaly/src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventsRepository::class)
 */
class Events
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $all_day;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_at_date;

    /**
     * @Assert\GreaterThanOrEqual(propertyPath="start_at_date")
     * @ORM\Column(type="datetime")
     */
    private $end_at_date;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="events")
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $bgcolor;

    /**
     * @ORM\Column(type="boolean")
     */
    private $shared;

    /**
     * @ORM\Column(type="boolean")
     */
    private $allow_modify;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Users::class, inversedBy="member_of_events")
     */
    private $members;

    public function __construct()
    {
        $this->shared = false;
        $this->allow_modify = false;
        $this->created_at = new DateTime("now");
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(?bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getStartAtDate(): ?DateTime
    {
        return $this->start_at_date;
    }

    public function setStartAtDate(DateTime $start_at_date): self
    {
        $this->start_at_date = $start_at_date;

        return $this;
    }

    public function getEndAtDate(): ?DateTime
    {
        return $this->end_at_date;
    }

    public function setEndAtDate(DateTime $end_at_date): self
    {
        $this->end_at_date = $end_at_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getBgcolor(): ?string
    {
        return $this->bgcolor;
    }

    public function setBgcolor(?string $bgcolor): self
    {
        $this->bgcolor = $bgcolor;

        return $this;
    }

    public function getShared(): ?bool
    {
        return $this->shared;
    }

    public function setShared(?bool $shared): self
    {
        $this->shared = $shared;

        return $this;
    }

    public function getAllowModify(): ?bool
    {
        return $this->allow_modify;
    }

    public function setAllowModify(?bool $allow_modify): self
    {
        $this->allow_modify = $allow_modify;

        return $this;
    }

    public function getCreatedAt(): ?DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Users[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }


    public function setMember(Users $member): bool
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            return true;
        }
        return false;
    }

    public function addMember(Users $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
        }

        return $this;
    }

    public function removeMember(Users $member): self
    {
        $this->members->removeElement($member);

        return $this;
    }

    /**
     * @param string $title
     * @param DateTime $start
     * @param DateTime $end
     * @param strinf $description
     * @return $this
     */
    public static  function construct(
        string $title,
        DateTime $start,
        DateTime $end,
        string $description

    ) {
        $event = new Events();
        $event->setTitle($title)
            ->setStartAtDate($start)
            ->setEndAtDate($end)
            ->setDescription($description);
        return $event;
    }
}

contacaly/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity("email", message="Le contenu de ce champ existe déjà.")
 * @Vich\Uploadable
 */
class Users implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @var string The hashed password
     */
    private $plainPasswordConf;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastConnection_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $subscripted_at;

    /**
     * @Assert\Length(min=10, max=14)
     * @Assert\Regex(pattern="/(^[+][^0][0-9]{10}$)|^(00)([^0])?([0-9]{2}||[0-9]{3})([0-9]{9}$)|^(0)[1-9][0-9]{8}$/",
     *     message="Ecrivez un vrai numéro de téléphone")
     * @ORM\Column(type="string", length=14, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $picture;

    /**
     * @Vich\UploadableField(mapping="profile_image", fileNameProperty="picture")
     * @var File | null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $infos;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Events::class, mappedBy="users", cascade={"remove"})
     * @ORM\JoinColumn(name="event_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $events;

    /**
     * @ORM\ManyToMany(targetEntity=Events::class, mappedBy="members")
     */
    private $member_of_events;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $job_title;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ContactCategory::class, mappedBy="user")
     */
    private $contactCategories;

    /**
     * @ORM\OneToMany(targetEntity=Contacts::class, mappedBy="user")
     */
    private $contacts;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $googleSub;

    public function __construct()
    {
        $this->subscripted_at = new \DateTime('now');
        $this->events = new ArrayCollection();
        $this->member_of_events = new ArrayCollection();
        $this->setRoles(['ROLE_USER']);
        $this->contactCategories = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastConnectionAt(): ?\DateTimeInterface
    {
        return $this->lastConnection_at;
    }

    public function setLastConnectionAt(?\DateTimeInterface $lastConnection_at): self
    {
        $this->lastConnection_at = $lastConnection_at;

        return $this;
    }

    public function getSubscriptedAt(): ?\DateTimeInterface
    {
        return $this->subscripted_at;
    }

    public function setSubscriptedAt(\DateTimeInterface $subscripted_at): self
    {
        $this->subscripted_at = $subscripted_at;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getInfos(): ?string
    {
        return $this->infos;
    }

    public function setInfos(?string $infos): self
    {
        $this->infos = $infos;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Events[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Events $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setUsers($this);
        }

        return $this;
    }

    public function removeEvent(Events $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getUsers() === $this) {
                $event->setUsers(null);
            }
        }

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection|Events[]
     */
    public function getMemberOfEvents(): Collection
    {
        return $this->member_of_events;
    }

    public function addMemberOfEvent(Events $memberOfEvent): self
    {
        if (!$this->member_of_events->contains($memberOfEvent)) {
            $this->member_of_events[] = $memberOfEvent;
            $memberOfEvent->addMember($this);
        }

        return $this;
    }

    public function removeMemberOfEvent(Events $memberOfEvent): self
    {
        if ($this->member_of_events->removeElement($memberOfEvent)) {
            $memberOfEvent->removeMember($this);
        }

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(?string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return File|UploadedFile|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|UploadedFile|null $imageFile
     * @return void
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
        return $this;
    }

    public function serialize()
    {
        return serialize([$this->id, $this->email, $this->password]);
    }

    public function unserialize($serialized)
    {

contacaly/src/Controller/Users/SearchController.php
<?php


namespace App\Controller\Users;


use App\Controller\Users\UsersController;
use App\Repository\EventsRepository;
use App\Repository\UsersRepository;
use DateTime;
use DateTimeZone;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SearchController extends AbstractController
{

    /**
     * @Route("/users/dashboard/calendar/search", name="dashboard-search", methods={"POST"})
     * @param UsersRepository $usersRepository
     * @return Response
     */
    public function dashboard_search(UsersRepository $usersRepository) :Response
    {
        //TODO - must find only users who shared calendar
        $users = $usersRepository->findAll();
        $users_json = [];
        foreach ($users as $user) {
            $users_json [] = [
                "id"=>$user->getId(),
                "email"=>$user->getEmail(),
                "name"=>$user->getName(),
                "lastname"=>$user->getLastname()??""
            ];
        }
        return new Response(json_encode($users_json),"200");
    }

}

contacaly/templates/users/calendar.html.twig
{%  extends 'base.html.twig' %}
{% block title %}Calendrier{% endblock %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block body %}

	<!--Content from viewer-->
	<div id="calendar" class="calendar main-content-calendar">

		<div class="main-content-calendar-inner">
			<div class="main-content-calendar-inner-calendar">

				<!--CALENDAR-->
				<div class="main-content-calendar-inner-calendar-calendar">
					<div id="calendar">
						{#		Dynamic content	from database			#}
					</div>
				</div>

			</div>

		</div>
	</div>

	<!--ADD EVENT-->
	<div class="main-content-event user_event_add  ">

		<div id="event" class="event">

			<div class="event-new">

				<div class="form">

					<form class="form-group" method="post" enctype="multipart/form-data">

						<div class="form-group-error my-alert my-alert-danger" id="eventFormError_js">
						</div>

						<input type="hidden" name="id" id="id">
						<div class="form-group-item">
							<label for="title">Titre*</label>
							<input type="text" name="title" id="title" placeholder="Titre">
						</div>

						<div class="form-group-item checkbox" id="all_days_js">
							<input type="checkbox" name="all_days" id="all_days">
							<label for="all_days">Toute la journée</label>
						</div>

						<div class="form-group-group ">

							<div class="form-group-item form-group-datetime">

								<div class="">
									<label for="start_at">Début*</label>
									<input type="date" name="start_at" id="start_at" placeholder="Début">
								</div>

								<div class="">
									<label for="start_at_time">Heure*</label>
									<input type="time" name="start_at_time" id="start_at_time" placeholder="Heure">
								</div>

							</div>

							<div class="form-group-item form-group-datetime">

								<div class="">
									<label for="end_at">Fin*</label>
									<input type="date" name="end_at" id="end_at" placeholder="Début">
								</div>

								<div class="">
									<label for="end_at_time">Heure*</label>
									<input type="time" name="end_at_time" id="end_at_time" placeholder="Heure">
								</div>

							</div>
							<!-- PROTECTION FRONT-END -->
							<div class="form-group-item form-group-datetime">
							</div>

						</div>

						<div class="form-group-item">
							<label for="description">Description*</label>
							<textarea name="description" id="description" cols="10" rows="2" placeholder="Description de l'événement"></textarea>
						</div>

						<div class="form-group-item">
							<div class="member_list" id="select2-viewer-members_js">
							</div>

							<label for="members">Inviter les membres</label>
							<select name="members" id="members" class="select2 members multiple_select2_js" multiple="multiple">
							</select>
						</div>

						<div class="form-group-item">
							<label for="location">Lieu</label>
							<input type="text" name="location" id="location" placeholder="Lieu. Ex : Strasbourg, Salle B3, Amphi Duramana (;--|)">
						</div>


						<div class="form-group-item">
							<label for="location">Choisissez une couleur de fond</label>
							<select  id="backgroundColor" name="backgroundColor">
								<option value="#4361EE">Bleue</option>
								<option value="#67C23A">Verte</option>
								<option value="#F56C6C">Rouge</option>
								<option value="#7209B7">Violette</option>
							</select>
						</div>

						<div class="form-group-item checkbox" id="shared_js">
							<input type="checkbox" name="shared" id="shared">
							<label for="shared">Partager votre événement</label>
						</div>

						<div class="form-group-item checkbox" id="allow_modify_js">
							<input type="checkbox" name="allow_modify" id="allow_modify">
							<label for="allow_modify">Permission aux modifications </label>
						</div>

						<div class="form-group-item">
							<small>* Champs obligatoires</small>
						</div>

						<div class="form-group-item">
							<button class="my-btn" id="user_event_add_return_btn_js"><i class="fal fa-backspace"></i></button>
							<button class="my-btn my-btn-danger" id="user_event_add_delete_btn_js"><i class="fal fa-trash-alt"></i></button>
							<button type="submit"  id="user_event_add_save_btn_js" class="my-btn my-btn-success"><i class="fal "></i></button>
						</div>

					</form>

				</div>
			</div>

		</div>

	</div>

	<!--ADD EVENT BTN -->
	{% if events is defined %}
		<div class="main-add-event-btn_css">
			<a class="add_event_js">
				<i class="far fa-calendar-plus"></i>
			</a>
		</div>
	{% endif %}

{%  endblock %}

{% block javascripts %}
	{{ parent() }}
	<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js" integrity="sha256-rPPF6R+AH/Gilj2aC00ZAuB2EKmnEjXlEWx5MkAp7bw=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.css" integrity="sha256-uq9PNlMzB+1h01Ij9cx7zeE2OR2pLAfRw3uUUOOPKdA=" crossorigin="anonymous">
	<link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>

	<script src="{{ asset('js/fullCalendar.js') }}"></script>

	<script>
		fullCalendarInit({{ events | raw }})
	</script>

{% endblock %}

contacaly/templates/users/dashboard.html.twig

{%  extends 'base.html.twig' %}
{% block title %}Dashboard{% endblock %}
{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block body %}

	<!--Content from viewer-->
	<div id="dashboard-u" class="dashboard-u main-content-dashboard">

		<div class="main-content-dashboard-inner">

			<!--Breadcrumb-->
			<div class="main-content-dashboard-inner-breadcrumb">
				<p>Bienvenu <strong>{{ app.user.name|upper  }}</strong>,</p>
			</div>

			<!--Statistic-->
			<div class="main-content-dashboard-inner-statistic">

				<div class="statistic">

					<!--USERS-->
					<div class="statistic-card card-user">
						<p><i class="fal fa-user-circle"></i></p>
						<div class="statistic-detail">
							<p>Nombre total de profils</p>
							<h3>{{ statistic.users | length }}</h3>
						</div>
					</div>

					<!--CONTACTS-->
					<div class="statistic-card card-contact">
						<p><i class="far fa-address-book"></i></p>
						<div class="statistic-detail">
							<p>Nombre total de contacts</p>
							<h3>{{ statistic.contacts| length }}</h3>
						</div>
					</div>

					<!--EVENTS-->
					<div class="statistic-card card-event">
						<p><i class="fal fa-calendar-day"></i></p>
						<div class="statistic-detail">
							<p>Nombre total d'événements</p>
							<h3>{{ statistic.events| length }}</h3>
						</div>
					</div>

					<!--MEMBERS-->
					<div class="statistic-card card-member">
						<p><i class="fal fa-object-group"></i></p>
						<div class="statistic-detail">
							<p>Nombre total de categories</p>
							<h3>{{ statistic.categories| length }}</h3>
						</div>
					</div>

				</div>

			</div>

			<!--DAILY-->
			<div class="main-content-dashboard-inner-body">

				<!--LEFT-->
				<div class="main-content-dashboard-inner-body-left">

					<!--TODAY-->
					<div class="main-content-dashboard-inner-body-left-today">

						<!--DATE SIDE-->
						<div class="current-top">
							<h2>{{ today.day }}</h2>
							<h5>{{ today.days }}</h5>
							<p>{{ today.month}} {{ today.year}}</p>
						</div>

						<!--EVENT SIDE-->
						{% if nearest_events  %}
							<div class="current-bottom">
								<!--EVENTS-->
								{% for today_event in nearest_events | sort((a,b)=> (a.startAtDate | date("d/m") > b.startAtDate | date("d/m")) ) %}
									<div class="current-bottom-event {{ (today_event.startAtDate | date("d/m/Y") == 'now' | date("d/m/Y"))?'today':''  }}">

										<p class="current-bottom-event-hour">
											<i class="fal fa-clock"></i>
											<small>{{ today_event.startAtDate  |date('H:i') }} - {{ today_event.endAtDate  |date('H:i') }}</small>
										</p>

										<h3><strong>{{ today_event.title }}</strong></h3>
										<p>{{ today_event.description }}</p>

										{% if today_event.location %}
											<p><i class="fal fa-map-marker-alt"></i>{{ today_event.location }}</p>
										{%  endif %}

										<div class="current-bottom-event-members">
											<!--MEMBER-->
											{% if today_event.members| length > 0 %}
												<div class="current-bottom-event-members">
													{% for member in today_event.members %}
														<!--MEMBER-->
														<div class="current-bottom-event-members-img">
															{% if member.picture %}
																<img src="{{ vich_uploader_asset(member, 'imageFile') }}" alt="image de {{ member.picture }}">
															{% else %}
																<img src="/images/profile/default/{{ member.picture??"man.jpg" }}" alt="image de {{ member.picture }}">
															{% endif %}
														</div>
													{% endfor %}
													<p> Membres</p>
												</div>
											{% endif %}
										</div>
									</div>
								{% endfor %}
							</div>
						{% else %}

						{% endif %}

					</div>

					<!--CALENDAR-->
					<div class="main-content-dashboard-inner-body-left-calendar">
						<div id="calendar"></div>
					</div>

				</div>

				<!--RIGHT-->
				<div class="main-content-dashboard-inner-body-right">

					<!--PROFILE SHORT VIEW-->
					<div class="main-content-dashboard-inner-body-right-profile">

						<!--PROFILE TITLE-->
						<div class="main-content-dashboard-inner-body-right-profile-title">
							<h3>Profil</h3>
						</div>

						<!--PROFILE BODY-->
						<div class="main-content-dashboard-inner-body-right-profile-body">

							<div class="main-content-dashboard-inner-body-right-profile-body-img">
								<div>
									{% if app.user.picture %}
										<img src="{{ vich_uploader_asset(app.user, 'imageFile') }}" alt="image de {{ app.user.picture }}">
									{% else %}
										<img src="/images/profile/default/man.jpg" alt="image de {{ app.user.picture }}">
									{% endif %}
								</div>
							</div>

							<div class="main-content-dashboard-inner-body-right-profile-body-names">
								<h4>{{ app.user.name|upper }} {{ app.user.lastname|capitalize }}</h4>
								<p>{{ app.user.jobtitle }}</p>
							</div>

							<hr>

							<div class="main-content-dashboard-inner-body-right-profile-body-stat">
								<!--CONTACTS ADDED BY THIS USERS-->
								<div id="profile-user">
									<i class="far fa-address-book"></i>
									<p>{{ app.user.contacts|length }}</p>
								</div>

								<!--MEMBERS ADDED BY THIS USERS-->
								<div id="profile-member">
									<i class="fal fa-users"></i>
									<p>{{ app.user.memberOfEvents|length }}</p>
								</div>

								<!--EVENTS ADDED BY THIS USERS-->
								<div id="profile-event">
									<i class="fal fa-calendar-day"></i>
									<p>{{ app.user.events | length }}</p>
								</div>
							</div>

						</div>

					</div>

					<!--CONTACTS NEW-->
					<div class="main-content-dashboard-inner-body-right-cont">
						<!--DATE SIDE-->
							<div class="current-top">
								<h3>Nouveaux contacts ajoutés</h3>
							</div>

						<!--EVENT SIDE-->
						{% if contacts | length > 0 %}

							<div class="current-bottom">
								<!--EVENTS-->
								{% for contact in contacts %}
									<div class="current-bottom-contact">

										<h3>
											<i class="fal fa-user"></i>
											<span>{{ contact.names }}</span>
										</h3>

										<p class="current-bottom-event-hour">
											<i class="fal fa-mobile-android"></i>
											<a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
										</p>

										<p>
											<i class="fal fa-at"></i>
											<a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
										</p>

										{% if contact.category %}
											<p>
												<i class="fal fa-building"></i>
												<span>{{ contact.category.category }}</span>
											</p>
										{% endif %}

									</div>
								{% endfor %}
							</div>

						{% else %}
							<div class="current-bottom">
								<div class="current-bottom-contact">
									<p>Pas de nouveau contact</p>
								</div>
							</div>
						{% endif %}

					</div>

				</div>

			</div>

		</div>

	</div>

{%  endblock %}

{% block javascripts %}
	{{ parent() }}

	<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.js"
			integrity="sha256-rPPF6R+AH/Gilj2aC00ZAuB2EKmnEjXlEWx5MkAp7bw="
			crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.1/main.min.css"
		  integrity="sha256-uq9PNlMzB+1h01Ij9cx7zeE2OR2pLAfRw3uUUOOPKdA="
		  crossorigin="anonymous">

	<link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css'
		  rel='stylesheet'>

	<script src="{{ asset('js/fullCalendar.js') }}"></script>

	<script>
		fullCalendarInit({{ events | raw }}, true);
	</script>

{% endblock %}