contacaly/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity("email", message="Le contenu de ce champ existe déjà.")
 * @Vich\Uploadable
 */
class Users implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @var string The hashed password
     */
    private $plainPasswordConf;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastConnection_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $subscripted_at;

    /**
     * @Assert\Length(min=10, max=14)
     * @Assert\Regex(pattern="/(^[+][^0][0-9]{10}$)|^(00)([^0])?([0-9]{2}||[0-9]{3})([0-9]{9}$)|^(0)[1-9][0-9]{8}$/",
     *     message="Ecrivez un vrai numéro de téléphone")
     * @ORM\Column(type="string", length=14, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $picture;

    /**
     * @Vich\UploadableField(mapping="profile_image", fileNameProperty="picture")
     * @var File | null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $infos;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Events::class, mappedBy="users", cascade={"remove"})
     * @ORM\JoinColumn(name="event_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $events;

    /**
     * @ORM\ManyToMany(targetEntity=Events::class, mappedBy="members")
     */
    private $member_of_events;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $job_title;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ContactCategory::class, mappedBy="user")
     */
    private $contactCategories;

    /**
     * @ORM\OneToMany(targetEntity=Contacts::class, mappedBy="user")
     */
    private $contacts;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $googleSub;

    public function __construct()
    {
        $this->subscripted_at = new \DateTime('now');
        $this->events = new ArrayCollection();
        $this->member_of_events = new ArrayCollection();
        $this->setRoles(['ROLE_USER']);
        $this->contactCategories = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastConnectionAt(): ?\DateTimeInterface
    {
        return $this->lastConnection_at;
    }

    public function setLastConnectionAt(?\DateTimeInterface $lastConnection_at): self
    {
        $this->lastConnection_at = $lastConnection_at;

        return $this;
    }

    public function getSubscriptedAt(): ?\DateTimeInterface
    {
        return $this->subscripted_at;
    }

    public function setSubscriptedAt(\DateTimeInterface $subscripted_at): self
    {
        $this->subscripted_at = $subscripted_at;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getInfos(): ?string
    {
        return $this->infos;
    }

    public function setInfos(?string $infos): self
    {
        $this->infos = $infos;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Events[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Events $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setUsers($this);
        }

        return $this;
    }

    public function removeEvent(Events $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getUsers() === $this) {
                $event->setUsers(null);
            }
        }

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection|Events[]
     */
    public function getMemberOfEvents(): Collection
    {
        return $this->member_of_events;
    }

    public function addMemberOfEvent(Events $memberOfEvent): self
    {
        if (!$this->member_of_events->contains($memberOfEvent)) {
            $this->member_of_events[] = $memberOfEvent;
            $memberOfEvent->addMember($this);
        }

        return $this;
    }

    public function removeMemberOfEvent(Events $memberOfEvent): self
    {
        if ($this->member_of_events->removeElement($memberOfEvent)) {
            $memberOfEvent->removeMember($this);
        }

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(?string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return File|UploadedFile|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|UploadedFile|null $imageFile
     * @return void
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
        return $this;
    }

    public function serialize()
    {
        return serialize([$this->id, $this->email, $this->password]);
    }

    public function unserialize($serialized)
    {

contacaly/src/Controller/Users/ContactsController.php
<?php

namespace App\Controller\Users;

use App\Entity\ContactCategory;
use App\Entity\Contacts;
use App\Form\ContactsType;
use App\Repository\ContactCategoryRepository;
use App\Repository\ContactsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ContactsController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $entityManager;
    /**
     * @var ContactsRepository $contactsRepository
     */
    private ContactsRepository $contactsRepository;

    /**
     * ContactsController constructor.
     * @param ContactsRepository $repository
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(
        ContactsRepository $repository,
        EntityManagerInterface $entityManager)
    {
        $this->contactsRepository   = $repository;
        $this->entityManager        = $entityManager;
    }

    /**
     * @Route("/users/contacts", name="users-contacts")
     * @param Request|null $request : useless when we make a search
     * @param ContactCategoryRepository $contactCategoryRepository
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(
        Request $request = null,
        ContactCategoryRepository $contactCategoryRepository,
        PaginatorInterface $paginator): Response
    {

        $request_array  = $request->query->all();
        $request_array_key_value = [];

        /**
         * Those categories will be used for select tag on front
         * @var ContactCategory $categories
         */
        $categories     = $contactCategoryRepository->findAll();
        foreach ($request_array as $key => $value) {
            if ($value) {
                $request_array_key_value[$key] = $value;
            }
        }

        /**
         * Doing search according options. Ex : Search by name, phone or categories
         */
        if ($request_array_key_value) {
            $contacts = $this->contactsRepository->findByOptions($request_array_key_value);
        } else {
            $contacts = $contacts ?? $this->contactsRepository->findAll();
        }

        $pagination = $paginator->paginate($contacts,$request->query->getInt('page',1),10);

        return $this->render(
            'users/contacts/index.html.twig',
            [
                'pagination' => $pagination,
                'search' => true,
                'desable' => true,
                'contact_active' => 'active',
                'categories' => $categories
            ]
        );
    }

    /**
     * @Route("/users/contacts/{id}/edit", name="users-contacts-edit", methods={"GET|POST"})
     * @Route("/users/contacts/new", name="users-contacts-new", methods={"GET|POST"})
     * @param int|null $id
     * @param Request $request
     * @return Response
     */
    public function edit(?int $id, Request $request): Response
    {
        if (!isset($id)) {
            $button_name= "Créer";
            $message    = "Création de contact avec succès";
            $title      = "Création de nouveau contact";
            $contact    = new Contacts();
            $contact->setUser($this->getUser());
        }else {
            $title      =  "Modification de contact";
            $button_name= "Edit";
            $message    = "Edition de contact avec succès";
            $contact    = $this->contactsRepository->find($id);
        }

        $form   = $this->createForm(ContactsType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->entityManager->persist($contact);
            $this->entityManager->flush();
            $this->addFlash("success", $message);
            return $this->redirectToRoute('users-contacts');
        }

        return $this->render(
            'users/contacts/add.html.twig',
            [
                'form' => $form->createView(),
                'button_name' => $button_name,
                'title' => $title
            ]
        );
    }

    /**
     * @Route("/users/contacts/delete/{id}", name="users-contacts-delete", methods={"POST", "DELETE"})
     * @param int $id
     * @param Request $request
     * @return Response
     */
    public function delete(int $id, Request $request): Response
    {
        $contact = $this->contactsRepository->find($id);
        if ($contact && $this->isCsrfTokenValid("delete" . $contact->getId(), $request->get('_token'))) {
            $this->entityManager->remove($contact);
            $this->entityManager->flush();
            $this->addFlash("success", "Suppression avec succès");
        }
        return $this->redirectToRoute("users-contacts");
    }

    /**
     * @Route("/users/search", name="search")
     * @param Request $request
     * @param ContactCategoryRepository $contactCategoryRepository
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function search(
        Request $request,
        ContactCategoryRepository $contactCategoryRepository,
        PaginatorInterface $paginator): Response
    {
        $request_array = $request->query->all();
        $request_array_key_value = [];
        $categories = $contactCategoryRepository->findAll();

        foreach ($request_array as $key => $value) {
            if ($value) {
                $request_array_key_value[$key] = $value;
            }
        }
        $contacts   = $this->contactsRepository->findByOptions($request_array_key_value);
        $pagination = $paginator->paginate($contacts,$request->query->getInt('page',1),10);

        return $this->render(
            'users/contacts/index.html.twig',
            [
                'pagination' => $pagination,
                'search' => true,
                'desable' => true,
                'categories' => $categories,
            ]
        );
    }
}

contacaly/src/Controller/Users/SearchController.php
<?php


namespace App\Controller\Users;


use App\Controller\Users\UsersController;
use App\Repository\EventsRepository;
use App\Repository\UsersRepository;
use DateTime;
use DateTimeZone;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SearchController extends AbstractController
{

    /**
     * @Route("/users/dashboard/calendar/search", name="dashboard-search", methods={"POST"})
     * @param UsersRepository $usersRepository
     * @return Response
     */
    public function dashboard_search(UsersRepository $usersRepository) :Response
    {
        //TODO - must find only users who shared calendar
        $users = $usersRepository->findAll();
        $users_json = [];
        foreach ($users as $user) {
            $users_json [] = [
                "id"=>$user->getId(),
                "email"=>$user->getEmail(),
                "name"=>$user->getName(),
                "lastname"=>$user->getLastname()??""
            ];
        }
        return new Response(json_encode($users_json),"200");
    }

}

contacaly/templates/users/users/edit.html.twig
{%  extends 'base.html.twig' %}
{% block title %}{{ button_message =="edit"?"Personnalisation de l'utilisateur":'Création de nouveau utilisateur' }}{% endblock %}

{%  block body %}


	<!--Content from viewer-->
	<div id="profile" class="main-content-user">
		<div class="main-content-user-profile">

			<div class="form">

				<div class="form-title">
					<h3>{{ button_message =="edit"?"Personnalisation de l'utilisateur":'Création de nouveau utilisateur' }}</h3>
				</div>

				<div class="row">

					{{ form_start(form, {attr:{'class':"form-group"}}) }}
						{{ form_row(form.name) }}
						{{ form_row(form.lastname) }}
						{{ form_row(form.email) }}
						{{ form_row(form.phone) }}
						{{ form_row(form.jobtitle) }}
						{{ form_row(form.infos) }}
						{{ form_row(form.imageFile) }}
					<div class="btns-area">
						<a href="{{ url }}" class="my-btn my-btn-secondary"><i class="fal fa-backspace"></i></a>
						<button type="submit" class="my-btn my-btn-success">{{ button_message =="edit"?'<i class="fal fa-pencil-alt"></i>':'<i class="fal fa-save"></i>' }}</button>
					</div>
					{{ form_end(form) }}
				</div>
			</div>

		</div>
	</div>

{%  endblock %}

contacaly/templates/users/users/profile.html.twig
{%  extends 'base.html.twig' %}

{% block title %}Profil d'utilisateur{% endblock %}

{% block body %}
	<!--Content from viewer-->
	<div id="profile" class="main-content-profile mainprofile">

		<div class="profile-inner">

			<!--SHOWCASE OR HEADER-->
			<div class="main-content-profile-inner-header">

				<!--BG-->
				<div class="main-content-profile-inner-header-img">
					<img src="/images/bg/profile_bg.jpg" alt="image">
				</div>

				<!--USER PROFILE-->
				<div
					class="main-content-profile-inner-header-profile">

					<!--PICTURE-->
					<div class="main-content-profile-inner-header-profile-picture">

						<div class="main-content-profile-inner-header-profile-picture-img">
							{% if app.user.picture %}
								<img src="{{ vich_uploader_asset(app.user, 'imageFile') }}" alt="image de {{ app.user.picture }}">
							{% else %}
								<img src="/images/profile/default/man.jpg" alt="image de {{ app.user.picture }}">
							{% endif %}
						</div>

						<div class="main-content-profile-inner-header-profile-picture-text">
							<h2>{{ user.name |upper }} {{ user.lastname|capitalize }}</h2>
							<p>{{ user.jobTitle |capitalize }}</p>
						</div>

					</div>

				</div>

			</div>

			<div class="main-content-profile-inner-calendarp">

				<div class="main-content-profile-inner-calendarp-left">

					<div class="main-content-profile-inner-calendarp-left-info">
						<h3>Informations personnelles</h3>
						<p>Nom : {{ user.name }}</p>
						<p>Prénom : {{ user.lastname }}</p>
						<p>Dernière connexion : {{ user.lastConnectionAt |date ('d-M-Y H:i') }}</p>
					</div>

					<div class="main-content-profile-inner-calendarp-left-pers">
						<h3>Informations professionnelles</h3>
						<p>Email : {{ user.email }}</p>
						<p>Phone : {{ user.phone }}</p>
						<p>Poste : {{ user.jobtitle }}</p>
					</div>

					<div class="main-content-profile-inner-calendarp-left-infos">
						<h3>Sur moi</h3>
						<p>{{ user.infos }}</p>
					</div>

					{% if app.user.id == user.id %}

						<div class="main-content-profile-inner-calendarp-left-button">
							<a href="{{ path('users-edit',{id:user.id}) }}" class="my-btn my-btn-success">
								Modifier mon compte
							</a>
							<form action="{{ path('users-delete',{id:user.id}) }}" method="POST"
								  style="display: inline-block" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer votre compte?')">
								<input type="hidden" name="_method" value="DELETE">
								<input type="hidden" name="role" value="user">
								<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
								<button type="submit" class="my-btn my-btn-danger" style="padding: .8rem 1rem;">Supprimer mon compte</button>
							</form>

						</div>

					{% endif %}

					{% for message in app.flashes('success') %}
					<div class="main-content-profile-inner-calendarp-left-infos">
						<div class="returnMessage">
								<p class="my-alert my-alert-success">{{ message }}</p>
						</div>
					</div>
					{% endfor %}
				</div>

				<!--CALENDAR-->
				<div class="main-content-profile-inner-calendarp-right">
					
				</div>

			</div>

		</div>
	</div>

{%  endblock %}